config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get '/signup' => 'users#new'
  post 'users' => 'users#create'

 get '/login' => 'sessions#new'
      post '/login' => 'sessions#create'
      get '/logout' => 'sessions#destroy'

resources :users
resources :websites
resources :settings
  get 'sessions/index'
  get 'sessions/show'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'sessions/update'
  get 'sessions/edit'

  get 'users/new'

  get 'users/create'

  get 'users/update'

  get 'users/edit'

  get 'users/destroy'

  get 'users/index'

  get 'users/show'

 

end

app/models/setting.rb
class Setting < ActiveRecord::Base
	belongs_to :user
	# after_create :defaults

 #    def defaults
	# 	self.frames ||= 1 
	# 	self.style ||= 1
	# 	self.skin ||= "white"
	# 	self.background ||= "white"
 #    end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_one :setting
	has_many :websites

	validates_presence_of :fname
	validates_presence_of :lname
	validates :email, uniqueness: { case_sensitive: true }
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	validates :password, length: { in: 4..20 }
	validates_presence_of :password 
	validates_confirmation_of :password
	

	after_create :set_defaults

    def set_defaults
		self.create_setting frames: 1, style: "1", skin: "white", background: "white", website1: "https://www.duckduckgo.com"
    end
end

app/models/website.rb
class Website < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


   def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      end
      helper_method :current_user

      def authorize
        #redirect_to '/login' unless current_user 
      end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


	def index
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end
#iets klopt hier niet
  def show
    @users = User.all
  end

  def new
  end

        def create
        user = User.find_by_email(params[:email])
        # If the user exists AND the password entered is correct.
        if user && user.authenticate(params[:password])
          session[:user_id] = user.id
          redirect_to '/'
        else
        # If user's login doesn't work, send them back to the login form.
          redirect_to '/login'
        end
      end

      def destroy
        session[:user_id] = nil
        redirect_to '/login'
      end

   def update
   end

  def edit
  end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def index
  end

  def show
  end


  def create
  end

  def update
    @user = User.find_by_id params[:user_id]
    @settings = @user.setting
    @settings.update setting_params
    redirect_to user_path @user
  end

  def destroy
  end

  def edit
  end

  private
  def setting_params
      params.require(:setting).permit(:style, :skin, :frames, :background, :website1, :website2, :website3, :website4)
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_filter :authorize

  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id params[:id]
    @settings = @user.setting
    if @settings.frames == 1
      render :oneframe
    elsif @settings.frames == 2
      render :twoframe
    elsif @settings.frames == 3
      render :threeframe
    elsif @settings.frames == 4
      render :fourframe
    end 
  end 

   def new
    @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "You have signed up for awesomeness:)"
        redirect_to '/login'
      else
        flash[:alert] = "nope"
        redirect_to '/signup'
      end
    end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "Your account has been deleted"
      redirect_to  '/signup'
    else
      flash[:alert] = "Something went wrong"
      redirect_to #users_page
  end
end

  def update
  end

  def edit
  end

  private
    def user_params
      params.require(:user).permit( :fname, :lname, :email, :password, :password_confirmation)
    end
  end
 

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
#methode CRUD
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def user_link user
		link_text = if user == current_user
						'you'
					else
						"#{user.fname} #{user.lname}"
					end
		link_to link_text, user_path(user)
	end

	def current_user
		@current_user ||= User.find_by_id(session[:user_id])
	end
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/home/index.html.erb
<img src="images/frames4.jpg" id="bg">

<h1>
	Welcome! IFrameYou!
</h1>
<!-- 
<p id="description">
	IFrameYou allows you to view up to four websites in one window. Just login (or sign up and login) to access this easy resource. Once you're in you'll see a menu icon on the top right corner. Click on it to select your user preferences and get started - easy peasy. Once you click submit, you'll find that YOU'VE BEEN FRAMED!
</p> -->

<!-- sign-up link -->

<div id="refs">
	<p class="click leftclick"><a href = "javascript:void(0)" onclick = "createlightbox('signup-lightbox')">sign<br>up </a></p>

	<p class="click rightclick"><a href = "javascript:void(0)" onclick = "createlightbox('login-lightbox')">login </a></p>
</div>

<table width="100%" align="left">
	<tr>
		<td>
		<div id="signup-lightbox" class="white_content" style="height:300px"> 
			<a href = "javascript:void(0)" onclick = "closelightbox('signup-lightbox')" style="float:right">
			<img src="http://2.bp.blogspot.com/-aXHXnOQPBJM/Tx_p1qqNI4I/AAAAAAAAAeU/bH0tlsikADQ/s1600/icon_cancel.gif" alt="" /></a>      
			<table align="center" cellpadding="5" cellspacing="5">
				<tr>
					<td colspan="2" class="Title" align="center">
						<span style="font-size:18px; color:rgba(0, 0, 0, 1)" >Signup Form</span>
					</td>
				</tr>

				<tr>
					<td class="label">              
						<span style="color:rgba(0, 0, 0, .6)">First Name:</span>
					</td>
					<td align="center">
						<input id="Text1" type="text" />
					</td>
				</tr>

				<tr>
					<td class="label">              
						<span style="color:rgba(0, 0, 0, .6)">Last Name:</span>
					</td>
					<td align="center">
						<input id="Text1" type="text" />
					</td>
				</tr>

				<tr>
					<td class="label">
						<span style="color:rgba(0, 0, 0, .6)">Email:</span>
					</td>
					<td align="center">
						<input id="Text1" type="text" />
					</td>
				</tr>

				<tr>
					<td class="label">
						<span style="color:rgba(0, 0, 0, .6)">Password:</span>
					</td>
					<td align="center">
						<input id="Text2" type="password"/>
					</td>
				</tr>

				<tr>
					<td class="label">
						<span style="color:rgba(0, 0, 0, .6)">Confirm-Password:</span>
					</td>
					<td align="center">
						<input id="Text3" type="password" />
					</td>
				</tr><br>

				<tr>
					<td colspan="2" class="Title" align="center"><br>
		<!-- 				<div style="align:center"> -->
						<input id="Button1" type="button" value="Sign-Up!" style="width:100px; height:30px; font-size:16px; background:rgb(0, 0, 0" />
						<!-- </div> -->
					</td>
				</tr>
			</table>
		</div>
		</td>
	</tr>
</table>   

<div id="fade" class="black_overlay"></div>


<!-- login form -->

<table width="100%" align="left">
	<tr>
		<td>
		<div id="login-lightbox" class="white_content" > 
			<a href = "javascript:void(0)" onclick = "closelightbox('login-lightbox')" style="float:right">
			<img src="http://2.bp.blogspot.com/-aXHXnOQPBJM/Tx_p1qqNI4I/AAAAAAAAAeU/bH0tlsikADQ/s1600/icon_cancel.gif" alt="" /></a>      
			<table align="center" cellpadding="5" cellspacing="5" >
				<tr>
					<td colspan="2" class="Title" align="center">
						<span style="font-size:18px; color:rgba(0, 0, 0, 1)" >Login Form</span>
					</td>
				</tr>
				<tr>
					<td class="label">              
						<span style="color:rgba(0, 0, 0, .6)">email:</span>
					</td>
					<td align="center">
						<input id="Text1" type="text" />
					</td>
				</tr>
				<tr>
					<td class="label">              
						<span style="color:rgba(0, 0, 0, .6)">Password:</span>
					</td>
					<td align="center">
						<input id="Text2" type="password" />
					</td>
				</tr>
				<tr><br>
					<td colspan="2" class="Title" align="center"><br>         
						<input id="Button1" type="button" value="Login!" style="width:100px; height:30px; font-size:16px; background:rgb(0, 0, 0"  />
					</td>
				</tr>	
			</table>
		</div>
		</td>
	</tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Iframeyou</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="usernav">
 <% if current_user %>
      Signed in as <%= current_user.fname %> <%= current_user.lname %> | <%= link_to "Logout", '/logout' %> 
    <% else %>
      ||<%= link_to 'Login', '/login' %> || <%= link_to 'Signup', '/signup' %>
    <% end %>
</div>

    <%= flash[:notice] %>
    <%= flash[:alert] %>

<div>
<% if current_user %>
  <a href="#" class="menu <%= @settings.background %>-bg <%= @settings.skin %>"><img src="/images/threebars.png" id="image"></a>

  <div class="settings <%= @settings.background %>-bg <%= @settings.skin %>">
    <a href="#" class="menubox"><img src="/images/threebars.png" id="image"></a>
    <br><br>

    <div class="category-box">
      <p>
        Frames and Layout
      </p>
      <div id="frames-and-layouts">
        <a href="#" class="options" data-field-value="1" data-field-number="1"><img src="/images/1.png" class="icon one"></a>
        <a href="#" class="options" data-field-value="2h" data-field-number="2"><img src="/images/2h.png" class="icon two"></a>
        <a href="#" class="options" data-field-value="2v" data-field-number="2"><img src="/images/2v.png" class="icon two"></a>
        <a href="#" class="options" data-field-value="3h" data-field-number="3"><img src="/images/3h.png" class="icon three"></a>
        <a href="#" class="options" data-field-value="3t"  data-field-number="3"><img src="/images/3t.png" class="icon three"></a>
        <a href="#" class="options" data-field-value="3b"  data-field-number="3"><img src="/images/3b.png" class="icon three"></a>
        <a href="#" class="options" data-field-value="4a" data-field-number="4"><img src="/images/4a.png" class="icon four"></a>
        <a href="#" class="options" data-field-value="4t" data-field-number="4"><img src="/images/4t.png" class="icon four"></a>
        <a href="#" class="options" data-field-value="4b" data-field-number="4"><img src="/images/4b.png" class="icon four"></a>
      </div>
    </div>
    <div class="category-box">
      <p>
        Skin
      </p>
      <div id="skin">
        <a href="#" class="options" data-field-value="black"><img src="/images/black.png" class="icon"></a>
        <a href="#" class="options" data-field-value="white"><img src="/images/white.png" class="icon"></a>
        <a href="#" class="options" data-field-value="pink"><img src="/images/pink.png" class="icon"></a>
        <a href="#" class="options" data-field-value="purple"><img src="/images/purple.png" class="icon"></a>
        <a href="#" class="options" data-field-value="blue"><img src="/images/blue.png" class="icon"></a>
      </div>
    </div>
    <div class="category-box">
    <p>
      Background
    </p>
      <div id="background">
        <a href="#" class="options" data-field-value="black"><img src="/images/black.png" class="icon"></a>
        <a href="#" class="options" data-field-value="white"><img src="/images/white.png" class="icon"></a>
        <a href="#" class="options" data-field-value="pink"><img src="/images/pink.png" class="icon"></a>
        <a href="#" class="options" data-field-value="purple"><img src="/images/purple.png" class="icon"></a>
        <a href="#" class="options" data-field-value="blue"><img src="/images/blue.png" class="icon"></a>
      </div>
    </div>
      <br><br>
    <%= form_for @settings, url: user_settings_path(@user) do |f| %>
    <%= f.hidden_field :frames %>
    <%= f.hidden_field :style %>
    <%= f.hidden_field :skin %>
    <%= f.hidden_field :background %>
    <div id="web1" class="categories">
    <%= f.label :website1, 'Website For Frame One' %><br>
    <%= f.text_field :website1 %><br><br>
    </div>
    <div id="web2" class="categories">
    <%= f.label :website2, 'Website For Frame Two' %><br>
    <%= f.text_field :website2 %><br><br>
    </div>
    <div id="web3" class="categories">
    <%= f.label :website3, 'Website For Frame Three' %><br>
    <%= f.text_field :website3 %><br><br>
    </div>
    <div id="web4" class="categories">
    <%= f.label :website4, 'Website For Frame Four' %><br>
    <%= f.text_field :website4 %><br><br>
    </div>
    <div id="submit">
      <%= f.submit 'Submit' %>
    </div>
    <% end %>
  </div>
</div>
<% end %>
<%= yield %>

</body>
</html>

app/views/settings/create.html.erb
<h1>Settings#create</h1>
<p>Find me in app/views/settings/create.html.erb</p>

app/views/settings/destroy.html.erb
<h1>Settings#destroy</h1>
<p>Find me in app/views/settings/destroy.html.erb</p>

app/views/settings/edit.html.erb
<h1>Settings#edit</h1>
<p>Find me in app/views/settings/edit.html.erb</p>

app/views/settings/index.html.erb
<h1>Settings#index</h1>
<p>Find me in app/views/settings/index.html.erb</p>

app/views/settings/new.html.erb
<h1>Settings#new</h1>
<p>Find me in app/views/settings/new.html.erb</p>

app/views/settings/show.html.erb
<h1>Settings#show</h1>
<p>Find me in app/views/settings/show.html.erb</p>

app/views/settings/update.html.erb
<h1>Settings#update</h1>
<p>Find me in app/views/settings/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/fourframe.html.erb
<% if @settings.style == "4a" %>
	<iframe src="<%= @settings.website1 %>" class="left <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website2 %>" class="right <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website3 %>" class="left <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website4 %>" class="right <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
<% elsif @settings.style == "4t" %>
	<iframe src="<%= @settings.website1 %>" class="full <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website2 %>" class="halfleftthree <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website3 %>" class="halfmiddlethree <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website4 %>" class="halfrightthree <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
<% elsif @settings.style == "4b" %>
	<iframe src="<%= @settings.website1 %>" class="halfleftthree <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website2 %>" class="halfmiddlethree <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website3 %>" class="halfrightthree <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website4 %>" class="full <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
<% end %>

app/views/users/index.html.erb
<img src="images/frames4.jpg" id="bg">

<h1>
	Welcome! IFrameYou!
</h1>
<!-- 
<p id="description">
	IFrameYou allows you to view up to four websites in one window. Just login (or sign up and login) to access this easy resource. Once you're in you'll see a menu icon on the top right corner. Click on it to select your user preferences and get started - easy peasy. Once you click submit, you'll find that YOU'VE BEEN FRAMED!
</p> -->

<!-- sign-up link -->

<div id="refs">
	<p class="click leftclick"><a href = "javascript:void(0)" onclick = "createlightbox('signup-lightbox')">sign<br>up </a></p>

	<p class="click rightclick"><a href = "javascript:void(0)" onclick = "createlightbox('login-lightbox')">login </a></p>
</div>

<table width="100%" align="left">
	<tr>
		<td>
		<div id="signup-lightbox" class="white_content" style="height:300px"> 
			<a href = "javascript:void(0)" onclick = "closelightbox('signup-lightbox')" style="float:right">
			<img src="http://2.bp.blogspot.com/-aXHXnOQPBJM/Tx_p1qqNI4I/AAAAAAAAAeU/bH0tlsikADQ/s1600/icon_cancel.gif" alt="" /></a>      
			<table align="center" cellpadding="5" cellspacing="5">
				<tr>
					<td colspan="2" class="Title" align="center">
						<span style="font-size:18px; color:rgba(0, 0, 0, 1)" >Signup Form</span>
					</td>
				</tr>

				<tr>
					<td class="label">              
						<span style="color:rgba(0, 0, 0, .6)">First Name:</span>
					</td>
					<td align="center">
						<input id="Text1" type="text" />
					</td>
				</tr>

				<tr>
					<td class="label">              
						<span style="color:rgba(0, 0, 0, .6)">Last Name:</span>
					</td>
					<td align="center">
						<input id="Text1" type="text" />
					</td>
				</tr>

				<tr>
					<td class="label">
						<span style="color:rgba(0, 0, 0, .6)">Email:</span>
					</td>
					<td align="center">
						<input id="Text1" type="text" />
					</td>
				</tr>

				<tr>
					<td class="label">
						<span style="color:rgba(0, 0, 0, .6)">Password:</span>
					</td>
					<td align="center">
						<input id="Text2" type="password"/>
					</td>
				</tr>

				<tr>
					<td class="label">
						<span style="color:rgba(0, 0, 0, .6)">Confirm-Password:</span>
					</td>
					<td align="center">
						<input id="Text3" type="password" />
					</td>
				</tr><br>

				<tr>
					<td colspan="2" class="Title" align="center"><br>
		<!-- 				<div style="align:center"> -->
						<input id="Button1" type="button" value="Sign-Up!" style="width:100px; height:30px; font-size:16px; background:rgb(0, 0, 0" />
						<!-- </div> -->
					</td>
				</tr>
			</table>
		</div>
		</td>
	</tr>
</table>   

<div id="fade" class="black_overlay"></div>


<!-- login form -->

<table width="100%" align="left">
	<tr>
		<td>
		<div id="login-lightbox" class="white_content" > 
			<a href = "javascript:void(0)" onclick = "closelightbox('login-lightbox')" style="float:right">
			<img src="http://2.bp.blogspot.com/-aXHXnOQPBJM/Tx_p1qqNI4I/AAAAAAAAAeU/bH0tlsikADQ/s1600/icon_cancel.gif" alt="" /></a>      
			<table align="center" cellpadding="5" cellspacing="5" >
				<tr>
					<td colspan="2" class="Title" align="center">
						<span style="font-size:18px; color:rgba(0, 0, 0, 1)" >Login Form</span>
					</td>
				</tr>
				<tr>
					<td class="label">              
						<span style="color:rgba(0, 0, 0, .6)">email:</span>
					</td>
					<td align="center">
						<input id="Text1" type="text" />
					</td>
				</tr>
				<tr>
					<td class="label">              
						<span style="color:rgba(0, 0, 0, .6)">Password:</span>
					</td>
					<td align="center">
						<input id="Text2" type="password" />
					</td>
				</tr>
				<tr><br>
					<td colspan="2" class="Title" align="center"><br>         
						<input id="Button1" type="button" value="Login!" style="width:100px; height:30px; font-size:16px; background:rgb(0, 0, 0"  />
					</td>
				</tr>	
			</table>
		</div>
		</td>
	</tr>
</table>

app/views/users/new.html.erb
  <h1>style needed!</h1>
  


  <% if @user.errors.full_messages.any?%>
  <ul>
   <% @user.errors.full_messages.each do |error_message| %>
   <li> <%= error_message %> </li> <br>
   <% end %>
  </ul>
  <% end %>	

<%= link_to "sign up", "#signup_form", class: "fancybox" %>
<div class="fanbox">
  <div style="display:none">
  <!-- <form id="signup_form" method="post" action="signup">
        <p id="signup_error">Sign up for awesomeness </p> -->


  <ul>  
   <%= form_for @user, url: '/users' do |f| %>
   <%= f.label :fname, 'Firstname' %>
   <%= f.text_field :fname %>
   <br> <br>
   <%= f.label :lname, 'Last' %>
   <%= f.text_field :lname %>
   <br> <br>
   <%= f.label :email, 'Email' %>
   <%= f.text_field :email %>
   <br> <br>
   <%= f.label :password, 'Password' %>
   <%= f.password_field :password %>
   <br> <br>
   <%= f.label :password_confirmation, 'Password Confirmation' %>
   <%= f.password_field :password_confirmation %>
   <br> <br>
   <%= f.submit :'Submit' %>
   <% end %>

  </ul>
     <p>
  <em> Resizing needed! </em>
    </p>
  <!-- </form> -->
 </div>
</div>

app/views/users/oneframe.html.erb
	<iframe src="<%= @settings.website1 %>" class="<%= @settings.background %>-bg <%= @settings.skin %>" id="fullscreen"></iframe>

app/views/users/random.html.erb
	<iframe src="https://www.duckduckgo.com" id="topleft" style="border-color: " + <%= @settings.skin %>;></iframe>

app/views/users/show.html.erb
<%= @user.fname %>
<%= @user.lname %>
<%= link_to "Delete yourself", user_path, methode: :delete %>

app/views/users/threeframe.html.erb
<% if @settings.style == "3h" %>
	<iframe src="<%= @settings.website1 %>" class="leftthree <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website2 %>" class="middlethree <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website3 %>" class="rightthree <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
<% elsif @settings.style == "3b" %>
	<iframe src="<%= @settings.website1 %>" class="left <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website2 %>" class="right <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website3 %>" class="full <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
<% elsif @settings.style == "3t" %>
	<iframe src="<%= @settings.website1 %>" class="full <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website2 %>" class="left <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website3 %>" class="right <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
<% end %>

app/views/users/twoframe.html.erb
<% if @settings.style == "2h" %>
	<iframe src="<%= @settings.website1 %>" class="full <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website2 %>" class="full <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
<% elsif @settings.style == "2v" %>
	<iframe src="<%= @settings.website1 %>" class="leftfull <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
	<iframe src="<%= @settings.website2 %>" class="rightfull <%= @settings.background %>-bg <%= @settings.skin %>"></iframe>
<% end %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/websites/create.html.erb
<h1>Websites#create</h1>
<p>Find me in app/views/websites/create.html.erb</p>

app/views/websites/destroy.html.erb
<h1>Websites#destroy</h1>
<p>Find me in app/views/websites/destroy.html.erb</p>

app/views/websites/edit.html.erb
<h1>Websites#edit</h1>
<p>Find me in app/views/websites/edit.html.erb</p>

app/views/websites/index.html.erb
<h1>Websites#index</h1>
<p>Find me in app/views/websites/index.html.erb</p>

app/views/websites/new.html.erb
<h1>Websites#new</h1>
<p>Find me in app/views/websites/new.html.erb</p>

app/views/websites/show.html.erb
<h1>Websites#show</h1>
<p>Find me in app/views/websites/show.html.erb</p>

app/views/websites/update.html.erb
<h1>Websites#update</h1>
<p>Find me in app/views/websites/update.html.erb</p>